name: Android CI

on:
  push:
    branches: [ "main" ]  # Trigger khi push lên nhánh main
  pull_request:
    branches: [ "main" ]  # Trigger khi có pull request lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Build trên hệ điều hành Ubuntu (Linux)

    steps:
      - name: Checkout source
        uses: actions/checkout@v3  # Lấy mã nguồn từ repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Cài đặt OpenJDK 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3  # Cài đặt Android SDK và các công cụ cần thiết

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # Cấp quyền thực thi cho gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug  # Build APK

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Upload APK để tải về sau
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk  # Đường dẫn tới APK